name: Deploy project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Code download
        uses: actions/checkout@v3
      - name: Install Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: 19
      - name: Install dependencies
        run: npm ci
      - name: Run Tests
        run: npm test
